import { create } from 'zustand';
import { GameState, School, StaffMember, TransferOffer, Enredo, EnredoCategory, SambaSelectionProcess, SambaEnredo } from '../types/models';
import { loadAllSchools } from '../data/schoolLoader';
import { INITIAL_MARKET_STAFF } from '../data/staffSeed';
import { calculateSalaryExpectation, ALL_ROLES } from '../utils/staffUtils';
import { loadRealStaff } from '../data/realStaff';
import { calculateStaffReputation, processRetirements, processStaffDevelopment } from '../services/staffService';
import {
  generateEnredoPool,
  revealNextStat,
  generateSingleEnredo,
  getCategoryWeightsForDivision,
  weightedRandomCategory,
  calculateTrendMap
} from '../services/researchEngine';
import { generateSambaSelectionProcess } from '../services/sambaEnredoEngine';
import { runSimulation, SimulationResult } from '../services/simulationService';
import { resolveOffer, processAITransfers } from '../services/transferService';
import { formatMoney } from '../utils/textUtils';

/**
 * Helper to initialize game data by merging real staff into schools and market.
 */
const initializeGameData = () => {
  // 1. Load Schools
  const schools = loadAllSchools();

  // 1a. Generate Enredos for AI Schools (to set trends)
  const aiSchools = schools; // All schools initially (player picks one later)
  const aiCategories: EnredoCategory[] = [];
  const schoolCategories = new Map<string, EnredoCategory>();

  // Assign Categories first
  aiSchools.forEach(school => {
    const weights = getCategoryWeightsForDivision(school.currentDivision);
    const category = weightedRandomCategory(weights);
    schoolCategories.set(school.id, category);
    aiCategories.push(category);
  });

  // Calculate Trend Map
  const trendMap = calculateTrendMap(aiCategories);

  // Generate Enredos for AI Schools
  aiSchools.forEach(school => {
    const category = schoolCategories.get(school.id)!;
    // Generate full enredo
    const enredo = generateSingleEnredo(category, school, trendMap, 2026);
    // Auto-select for AI (they don't research)
    school.enredo = enredo;
    // AI schools also get a pool technically, but we just lock one in for simplicity
    school.enredoCandidates = [];
  });

  // 2. Load Real Staff
  const realStaffRaw = loadRealStaff();
  const realFreeAgents: StaffMember[] = [];

  // 3. Process Real Staff
  realStaffRaw.forEach(raw => {
    // Calculate Reputation
    const reputation = calculateStaffReputation(raw as any, 2026); // Assume 2026 start

    // Find Target School to determine division context for salary
    // We cast raw to any to access _schoolName safely
    const rawAny = raw as any;
    const targetSchool = schools.find(s => s.name === rawAny._schoolName);

    // Per requirements: Real staff are legends/top-tier, so they always use 'Grupo Especial' context
    // regardless of their current school's division.
    const division = 'Grupo Especial';

    // Calculate Salary Expectation
    const salaryExpectation = calculateSalaryExpectation(raw.role, raw.skills, reputation, division, raw.archetype);

    // Complete Staff Object
    const staff: StaffMember = {
      id: raw.id,
      name: raw.name,
      role: raw.role,
      skills: raw.skills,
      archetype: raw.archetype,
      partnerId: raw.partnerId,
      historyText: raw.historyText,
      achievements: raw.achievements,
      reputation,
      salaryExpectation,
      salary: 0,
      contractYears: 0,
      currentSchoolId: null, // Will be set below
      age: raw.age,
      potential: undefined // Real staff have no potential (ceiling reached or custom logic)
    };

    if (targetSchool) {
      // Assign to School
      staff.currentSchoolId = targetSchool.id;
      staff.contractYears = 1; // Assume 1 year contract
      staff.salary = salaryExpectation; // Assume they are paid their worth

      // Remove existing GENERIC staff in that role if any.
      // We keep other Real Staff (e.g. for Duos like Gabriel Haddad & Leonardo Bora).
      const genericStaffInRole = targetSchool.staff.filter(s =>
        s.role === staff.role &&
        !realStaffRaw.some(r => r.id === s.id)
      );

      genericStaffInRole.forEach(generic => {
        const idx = targetSchool.staff.indexOf(generic);
        if (idx !== -1) targetSchool.staff.splice(idx, 1);
      });

      targetSchool.staff.push(staff);
    } else {
      // Free Agent (e.g. SP schools not in DB)
      realFreeAgents.push(staff);
    }
  });

  // 4. Load Random Market Staff (Initial)
  // Filter out names that exist in realStaff to avoid duplicates (e.g. Paulo Barros generated by seed)
  const realNames = new Set(realStaffRaw.map(s => s.name));

  const marketStaff = INITIAL_MARKET_STAFF.filter(s => !realNames.has(s.name));

  // Combine Free Agents
  // We put realFreeAgents FIRST so they appear at the top
  const availableStaff = [...realFreeAgents, ...marketStaff];

  return { schools, availableStaff };
};

const { schools: initialSchools, availableStaff: initialStaff } = initializeGameData();

/**
 * Calculates the displayed salary expectation adjusted by the school's prestige.
 * Higher prestige schools see a lower "effective price" because staff want to work there.
 */
export const calculateAdjustedSalary = (staff: StaffMember, schoolPrestige: number): number => {
  if (staff.role === 'RainhaDeBateria' && staff.archetype !== 'CriaDaComunidade') {
    return 0; // Celebrity and PostoPago don't have salary negotiation in the same way
  }

  const prestigeMultiplier = 1 + ((schoolPrestige - 100) / 500);
  const safeMultiplier = Math.max(0.1, prestigeMultiplier);

  return Math.ceil(staff.salaryExpectation / safeMultiplier);
};

/**
 * GameStoreState defines the shape of the global game state managed by Zustand.
 * It includes the current game status, the list of schools, and actions to modify the state.
 */
interface GameStoreState {
  gameState: GameState;
  schools: School[];
  availableStaff: StaffMember[];
  simulationResults: SimulationResult | null;

  // Actions
  setPlayerSchool: (schoolId: string) => void;
  advanceWeek: () => void;
  submitTransferOffer: (schoolId: string, staffId: string, offeredSalary: number, contractYears: number) => string;
  acceptCounter: (offerId: string) => void;
  rejectCounter: (offerId: string) => void;
  runPrestigeSimulation: (years: number) => void;

  // Enredo Actions
  focusResearch: (enredoId: string) => void;
  lockInEnredo: (enredoId: string) => void;
  chooseSamba: (sambaId: string) => void;
}

/**
 * useGameStore is the Zustand hook for accessing and updating the game state.
 * It initializes with the seed data and default game state.
 */
export const useGameStore = create<GameStoreState>((set, get) => ({
  gameState: {
    currentYear: 2026,
    currentWeek: 1,
    currentPhase: 'Market',
    playerSchoolId: null,
    pendingOffers: [],
    resolvedOffers: [],
    transferNews: [],
    hallOfFame: [],
    showEnredoDeadlineScreen: false,
    pendingSambaSelection: null,
    chosenSambaEnredo: null
  },
  schools: initialSchools,
  availableStaff: initialStaff,
  simulationResults: null,

  setPlayerSchool: (schoolId) =>
    set((state) => {
      // 1. Identify trends from other schools (which already have Enredos assigned in Init)
      const otherSchools = state.schools.filter(s => s.id !== schoolId && s.enredo);
      const categories = otherSchools.map(s => s.enredo!.category);

      const updatedSchools = state.schools.map((school) => {
        if (school.id === schoolId) {
          // Player School: Clear AI choice, generate pool
          const pool = generateEnredoPool(school, state.gameState.currentYear, categories);
          return {
            ...school,
            isPlayerControlled: true,
            enredo: null,
            enredoCandidates: pool,
            researchFocusId: null
          };
        }
        return {
          ...school,
          isPlayerControlled: false,
        };
      });

      return {
        schools: updatedSchools,
        gameState: {
          ...state.gameState,
          playerSchoolId: schoolId,
        },
      };
    }),

  advanceWeek: () =>
    set((state) => {
      // 1. Process Logic for current week (before advancing)
      const { currentYear, currentWeek, currentPhase, pendingOffers } = state.gameState;

      let updatedSchools = [...state.schools];
      let updatedAvailableStaff = [...state.availableStaff];
      let newResolvedOffers = [...state.gameState.resolvedOffers];
      // Close button clears resolvedOffers from view, so we assume we start fresh or append.
      // Given the UI logic, let's clear them so we only show new ones.
      newResolvedOffers = [];

      let newTransferNews = [...state.gameState.transferNews];
      // Reset news? Usually yes for a new week update.
      newTransferNews = [];

      if (currentPhase === 'Market') {
        // A. Resolve Player Offers
        const pending = [...pendingOffers];

        pending.forEach(offer => {
            if (offer.status !== 'Pending') {
                newResolvedOffers.push(offer);
                return;
            }

            const schoolIdx = updatedSchools.findIndex(s => s.id === offer.fromSchoolId);
            const staffIdx = updatedAvailableStaff.findIndex(s => s.id === offer.toStaffId);
            let staff = updatedAvailableStaff[staffIdx];

            if (!staff) {
                // Check schools
                for (const s of updatedSchools) {
                    const found = s.staff.find(st => st.id === offer.toStaffId);
                    if (found) {
                        staff = found;
                        break;
                    }
                }
            }

            if (!staff || schoolIdx === -1) {
                offer.status = 'Rejected';
                newResolvedOffers.push(offer);
                return;
            }

            const school = updatedSchools[schoolIdx];
            const unfilledRolesCount = ALL_ROLES.filter(role => !school.staff.some(s => s.role === role)).length;

            const resolved = resolveOffer(offer, staff, school, currentWeek, 8, unfilledRolesCount);

            if (resolved.status === 'Accepted') {
                // Execute Hire
                if (staff.currentSchoolId) {
                    const oldSchoolIdx = updatedSchools.findIndex(s => s.id === staff.currentSchoolId);
                    if (oldSchoolIdx !== -1) {
                        const oldSchool = updatedSchools[oldSchoolIdx];
                        oldSchool.staff = oldSchool.staff.filter(s => s.id !== staff.id);
                        updatedSchools[oldSchoolIdx] = { ...oldSchool };
                    }
                } else {
                    updatedAvailableStaff = updatedAvailableStaff.filter(s => s.id !== staff.id);
                }

                const existingStaffIdx = school.staff.findIndex(s => s.role === staff.role);
                if (existingStaffIdx !== -1) {
                    const fired = school.staff[existingStaffIdx];
                    fired.currentSchoolId = null;
                    fired.salary = 0;
                    fired.contractYears = 0;
                    updatedAvailableStaff.push(fired);
                    school.staff = school.staff.filter(s => s.id !== fired.id);
                }

                const newStaff = {
                    ...staff,
                    currentSchoolId: school.id,
                    salary: offer.offeredSalary,
                    contractYears: offer.contractYears
                };
                school.staff.push(newStaff);
                school.budget -= offer.offeredSalary;

                const prestigeBonus = Math.max(0, (staff.reputation - school.prestige) * 0.02);
                school.prestige = Math.min(195, school.prestige + prestigeBonus);

                updatedSchools[schoolIdx] = { ...school };
            }

            newResolvedOffers.push(resolved);
        });

        // B. Run AI Transfers
        const aiResult = processAITransfers(updatedSchools, updatedAvailableStaff, currentWeek, 8);
        updatedSchools = aiResult.updatedSchools;
        updatedAvailableStaff = aiResult.updatedStaff;
        newTransferNews = aiResult.news;
      }

      // 2. Advance Time
      let nextWeek = currentWeek + 1;
      let nextYear = currentYear;

      if (nextWeek > 52) {
        nextWeek = 1;
        nextYear += 1;
      }

      // Check for Enredo Deadline Block (Week 8 -> 9)
      let blockAdvancement = false;
      let showDeadline = false;
      let pendingSambaSelection = state.gameState.pendingSambaSelection;

      if (state.gameState.playerSchoolId && currentWeek === 8 && nextWeek === 9) {
          const pSchool = updatedSchools.find(s => s.id === state.gameState.playerSchoolId);
          if (pSchool) {
             if (!pSchool.enredo) {
                 // BLOCK: No enredo chosen
                 blockAdvancement = true;
                 showDeadline = true;
                 nextWeek = currentWeek; // Stay in week 8
                 nextYear = currentYear;
             } else {
                 // Enredo chosen: Ensure Samba Selection is generated
                 if (!pendingSambaSelection && !state.gameState.chosenSambaEnredo) {
                     pendingSambaSelection = generateSambaSelectionProcess(pSchool.enredo, pSchool);
                 }
             }
          }
      }

      let nextPhase: GameState['currentPhase'] = 'Market';
      if (nextWeek >= 1 && nextWeek <= 8) {
        nextPhase = 'Market';
      } else if (nextWeek >= 9 && nextWeek <= 44) {
        nextPhase = 'Preparation';
      } else if (nextWeek === 45) {
        nextPhase = 'Parade';
      } else {
        nextPhase = 'Results/Offseason';
      }

      // -- NEW LOGIC START --

      // Research Progress & Enredo Management
      if (state.gameState.playerSchoolId) {
        const pSchoolIdx = updatedSchools.findIndex(s => s.id === state.gameState.playerSchoolId);
        if (pSchoolIdx !== -1) {
            let pSchool = updatedSchools[pSchoolIdx];

            // 1. Research Progress (Weekly)
            if (pSchool.researchFocusId && pSchool.enredoCandidates) {
                const candIdx = pSchool.enredoCandidates.findIndex(e => e.id === pSchool.researchFocusId);
                if (candIdx !== -1) {
                    const candidate = pSchool.enredoCandidates[candIdx];
                    const newCandidate = revealNextStat(candidate);

                    const newCandidates = [...pSchool.enredoCandidates];
                    newCandidates[candIdx] = newCandidate;

                    pSchool = { ...pSchool, enredoCandidates: newCandidates };

                    if (newCandidate.statsRevealed >= 5) {
                         pSchool.researchFocusId = null;
                         newTransferNews.push(`Research complete for "${newCandidate.title}"`);
                    }
                }
            }

            // 2. Market Deadline / Preparation Start (Week 8 -> 9)
            // Note: We handled the BLOCK logic above. Here we handle the transition effects if we ARE advancing.
            if (!blockAdvancement && currentWeek === 8 && nextWeek === 9) {
                 if (pSchool.enredo) {
                     let budgetAdd = 0;
                     if (pSchool.enredo.sponsorValue > 0) {
                         const income = (pSchool.enredo.sponsorValue / 100) * pSchool.budget * 0.4;
                         budgetAdd = income;
                         newTransferNews.push(`Sponsorship for "${pSchool.enredo.title}" added ${formatMoney(income)}.`);
                     }

                     // Initial Morale Boost/Hit from Appeal
                     const moraleChange = Math.floor((pSchool.enredo.appeal - 50) / 10);
                     let newMorale = pSchool.fanbaseMorale + moraleChange;
                     newMorale = Math.max(0, Math.min(100, newMorale));

                     if (moraleChange !== 0) {
                        newTransferNews.push(`Enredo appeal changed morale by ${moraleChange > 0 ? '+' : ''}${moraleChange}.`);
                     }

                     pSchool = {
                         ...pSchool,
                         budget: pSchool.budget + budgetAdd,
                         fanbaseMorale: newMorale
                     };
                 }
            }

            // 3. Weekly Preparation Updates (Weeks 9-44) - Passive Morale Drift
            if (nextPhase === 'Preparation' && pSchool.enredo) {
                 // Appeal 50 is neutral. >50 gains, <50 loses.
                 // Small drift: (Appeal - 50) / 20 per week.
                 const drift = (pSchool.enredo.appeal - 50) / 20;
                 const chance = Math.abs(drift);
                 const sign = Math.sign(drift);

                 let change = Math.floor(chance);
                 if (Math.random() < (chance - change)) {
                     change += 1;
                 }

                 if (change > 0) {
                     const newMorale = Math.max(0, Math.min(100, pSchool.fanbaseMorale + (change * sign)));
                     pSchool = { ...pSchool, fanbaseMorale: newMorale };
                 }
            }

            updatedSchools[pSchoolIdx] = pSchool;
        }
      }

      // Retirement Check (Start of Market / Week 1)
      let hallOfFame = [...state.gameState.hallOfFame || []];

      if (nextWeek === 1) {
          // Process Available Staff
          const retAvail = processRetirements(updatedAvailableStaff);
          updatedAvailableStaff = retAvail.remaining;

          retAvail.retired.forEach(r => {
              if (r.reputation >= 200) hallOfFame.push(r);
              newTransferNews.push(`${r.name} (${r.role}) retired.`);
          });

          // Process Schools Staff
          updatedSchools = updatedSchools.map(school => {
             const retSchool = processRetirements(school.staff);

             retSchool.retired.forEach(r => {
                 if (r.reputation >= 200) hallOfFame.push(r);
                 newTransferNews.push(`${r.name} (${r.role}, ${school.name}) retired.`);
             });

             return { ...school, staff: retSchool.remaining };
          });
      }

      // Development Check (Start of Results/Offseason)
      if (nextWeek === 46) {
          // Process Player School Development
          const playerSchoolIndex = updatedSchools.findIndex(s => s.id === state.gameState.playerSchoolId);
          if (playerSchoolIndex !== -1) {
              const playerSchool = updatedSchools[playerSchoolIndex];
              // Get Score
              let score = 50;
              // Simple heuristic if no simulation result available
              if (playerSchool.prestige > 150) score = 70 + (Math.random() * 20);
              else score = 50 + (Math.random() * 20);

              const devResult = processStaffDevelopment(playerSchool.staff, score);
              updatedSchools[playerSchoolIndex] = { ...playerSchool, staff: devResult.updatedStaff };

              devResult.updates.forEach(u => newTransferNews.push(u));
          }
      }
      // -- NEW LOGIC END --

      return {
        schools: updatedSchools,
        availableStaff: updatedAvailableStaff,
        gameState: {
          ...state.gameState,
          currentYear: nextYear,
          currentWeek: nextWeek,
          currentPhase: nextPhase,
          pendingOffers: [],
          resolvedOffers: newResolvedOffers,
          transferNews: newTransferNews,
          hallOfFame
        },
      };
    }),

  submitTransferOffer: (schoolId, staffId, offeredSalary, contractYears) => {
    const state = get();
    const { currentWeek, currentPhase, pendingOffers } = state.gameState;

    if (currentPhase !== 'Market') return 'Transfer market is closed.';

    const school = state.schools.find(s => s.id === schoolId);
    let staff = state.availableStaff.find(s => s.id === staffId);
    if (!staff) {
        for (const s of state.schools) {
            staff = s.staff.find(st => st.id === staffId);
            if (staff) break;
        }
    }

    if (!school) return 'School not found.';
    if (!staff) return 'Staff not found.';

    if (school.budget < offeredSalary) return 'Insufficient budget.';

    const conflict = pendingOffers.find(o => {
        if (o.fromSchoolId !== schoolId || o.status !== 'Pending' || o.weekMade !== currentWeek) return false;
        let targetStaff = state.availableStaff.find(s => s.id === o.toStaffId);
        if (!targetStaff) {
             for (const s of state.schools) {
                targetStaff = s.staff.find(st => st.id === o.toStaffId);
                if (targetStaff) break;
            }
        }
        return targetStaff && targetStaff.role === staff.role;
    });

    if (conflict) return 'You can only make one offer per role per week.';

    const offer: TransferOffer = {
        id: `offer-${Date.now()}-${Math.random()}`,
        fromSchoolId: schoolId,
        toStaffId: staffId,
        offeredSalary,
        contractYears,
        weekMade: currentWeek,
        status: 'Pending'
    };

    set(state => ({
        gameState: {
            ...state.gameState,
            pendingOffers: [...state.gameState.pendingOffers, offer]
        }
    }));

    return 'Offer submitted successfully.';
  },

  acceptCounter: (offerId) => {
    const state = get();
    const offerIndex = state.gameState.resolvedOffers.findIndex(o => o.id === offerId);
    if (offerIndex === -1) return;

    const offer = state.gameState.resolvedOffers[offerIndex];
    if (offer.status !== 'Countered' || !offer.counterSalary) return;

    const updatedSchools = [...state.schools];
    let updatedAvailableStaff = [...state.availableStaff];

    const schoolIdx = updatedSchools.findIndex(s => s.id === offer.fromSchoolId);
    let staff = updatedAvailableStaff.find(s => s.id === offer.toStaffId);

    if (!staff) {
        for (const s of updatedSchools) {
            const found = s.staff.find(st => st.id === offer.toStaffId);
            if (found) {
                staff = found;
                break;
            }
        }
    }

    if (schoolIdx === -1 || !staff) return;
    const school = updatedSchools[schoolIdx];

    if (school.budget < offer.counterSalary) {
        return;
    }

    if (staff.currentSchoolId) {
        const oldSchoolIdx = updatedSchools.findIndex(s => s.id === staff.currentSchoolId);
        if (oldSchoolIdx !== -1) {
            const oldSchool = updatedSchools[oldSchoolIdx];
            oldSchool.staff = oldSchool.staff.filter(s => s.id !== staff!.id);
            updatedSchools[oldSchoolIdx] = { ...oldSchool };
        }
    } else {
        updatedAvailableStaff = updatedAvailableStaff.filter(s => s.id !== staff!.id);
    }

    const existingStaffIdx = school.staff.findIndex(s => s.role === staff!.role);
    if (existingStaffIdx !== -1) {
        const fired = school.staff[existingStaffIdx];
        fired.currentSchoolId = null;
        fired.salary = 0;
        fired.contractYears = 0;
        updatedAvailableStaff.push(fired);
        school.staff = school.staff.filter(s => s.id !== fired.id);
    }

    const newStaff = {
        ...staff,
        currentSchoolId: school.id,
        salary: offer.counterSalary,
        contractYears: offer.counterYears || 1
    };
    school.staff.push(newStaff);
    school.budget -= offer.counterSalary;

    const prestigeBonus = Math.max(0, (staff.reputation - school.prestige) * 0.02);
    school.prestige = Math.min(195, school.prestige + prestigeBonus);

    updatedSchools[schoolIdx] = { ...school };

    const updatedResolvedOffers = [...state.gameState.resolvedOffers];
    updatedResolvedOffers[offerIndex] = { ...offer, status: 'Accepted' };

    set({
        schools: updatedSchools,
        availableStaff: updatedAvailableStaff,
        gameState: {
            ...state.gameState,
            resolvedOffers: updatedResolvedOffers
        }
    });
  },

  rejectCounter: (offerId) => {
    set(state => ({
        gameState: {
            ...state.gameState,
            resolvedOffers: state.gameState.resolvedOffers.map(o =>
                o.id === offerId ? { ...o, status: 'Rejected' } : o
            )
        }
    }));
  },

  focusResearch: (enredoId) =>
    set((state) => {
      const playerSchoolIndex = state.schools.findIndex(s => s.id === state.gameState.playerSchoolId);
      if (playerSchoolIndex === -1) return {};

      const school = { ...state.schools[playerSchoolIndex] };
      // Verify enredo is in candidates
      if (!school.enredoCandidates?.some(e => e.id === enredoId)) return {};

      school.researchFocusId = enredoId;

      const updatedSchools = [...state.schools];
      updatedSchools[playerSchoolIndex] = school;

      return { schools: updatedSchools };
    }),

  lockInEnredo: (enredoId) =>
    set((state) => {
      const playerSchoolIndex = state.schools.findIndex(s => s.id === state.gameState.playerSchoolId);
      if (playerSchoolIndex === -1) return {};

      const school = { ...state.schools[playerSchoolIndex] };
      const selected = school.enredoCandidates?.find(e => e.id === enredoId);

      if (!selected) return {};

      school.enredo = selected;
      school.enredoCandidates = []; // Clear pool
      school.researchFocusId = null;

      // Generate Samba Selection Process immediately
      const pendingSambaSelection = generateSambaSelectionProcess(selected, school);

      const updatedSchools = [...state.schools];
      updatedSchools[playerSchoolIndex] = school;

      return {
        schools: updatedSchools,
        gameState: {
            ...state.gameState,
            showEnredoDeadlineScreen: false,
            pendingSambaSelection
        }
      };
    }),

  chooseSamba: (sambaId) =>
    set((state) => {
      if (sambaId === '__comprado__') {
        const custo_map: Record<string, number> = {
          'Grupo Especial': 500000, 'Série Ouro': 100000,
          'Série Prata': 30000, 'Série Bronze': 10000, 'Grupo de Avaliação': 3000,
        };
        const school = state.schools.find(s => s.id === state.gameState.playerSchoolId);
        if (!school) return {};
        const custo = custo_map[school.currentDivision] ?? 10000;

        const sambaComprado: SambaEnredo = {
          id: '__comprado__',
          title: `Samba Encomendado — ${school.enredo?.title ?? 'Enredo Oficial'}`,
          compositors: ['Compositores Contratados'],
          melodia: Math.floor(Math.random() * 15) + 78,       // 78-92
          grito: Math.floor(Math.random() * 15) + 72,          // 72-86
          apeloComunidade: Math.floor(Math.random() * 20) + 55, // 55-74 (less "soul")
          isEncomendado: true,
          letra: Math.floor(Math.random() * 15) + 80,
          ritmo: Math.floor(Math.random() * 10) + 82,
          sinergiaBateria: Math.floor(Math.random() * 15) + 70,
          emocao: Math.floor(Math.random() * 20) + 60,
          aderenciaAoEnredo: 95,
          versatilidade: 80
        };

        // Deduct cost from school budget
        const schoolIdx = state.schools.findIndex(s => s.id === state.gameState.playerSchoolId);
        const updatedSchools = [...state.schools];
        updatedSchools[schoolIdx] = { ...school, budget: school.budget - custo, sambaEnredo: sambaComprado };

        return {
          schools: updatedSchools,
          gameState: {
            ...state.gameState,
            chosenSambaEnredo: sambaComprado,
            pendingSambaSelection: null,
             transferNews: [
              ...state.gameState.transferNews,
              `🎵 Samba-Enredo ENCOMENDADO: "${sambaComprado.title}"!`
            ]
          }
        };
      }

      if (!state.gameState.pendingSambaSelection) return {};

      const chosen = state.gameState.pendingSambaSelection.candidates.find(s => s.id === sambaId);
      if (!chosen) return {};

      const playerSchoolIndex = state.schools.findIndex(s => s.id === state.gameState.playerSchoolId);
      if (playerSchoolIndex === -1) return {};

      const school = {
          ...state.schools[playerSchoolIndex],
          sambaEnredo: chosen
      };

      const updatedSchools = [...state.schools];
      updatedSchools[playerSchoolIndex] = school;

      return {
        schools: updatedSchools,
        gameState: {
          ...state.gameState,
          chosenSambaEnredo: chosen,
          pendingSambaSelection: null,
          transferNews: [
            ...state.gameState.transferNews,
            `🎵 Samba-Enredo escolhido: "${chosen.title}"!`
          ]
        }
      };
    }),

  runPrestigeSimulation: (years) => {
    const state = get();
    const results = runSimulation(state.schools, state.gameState.currentYear, years);
    set({ simulationResults: results });
  },
}));
