import { create } from 'zustand';
import { GameState, School, StaffMember, TransferOffer } from '../types/models';
import { loadAllSchools } from '../data/schoolLoader';
import { INITIAL_MARKET_STAFF, calculateSalaryExpectation } from '../data/staffSeed';
import { loadRealStaff } from '../data/realStaff';
import { calculateStaffReputation } from '../services/staffService';
import { researchEnredo } from '../services/researchEngine';
import { runSimulation, SimulationResult } from '../services/simulationService';
import { resolveOffer, processAITransfers } from '../services/transferService';

/**
 * Helper to initialize game data by merging real staff into schools and market.
 */
const initializeGameData = () => {
  // 1. Load Schools
  const schools = loadAllSchools();

  // 2. Load Real Staff
  const realStaffRaw = loadRealStaff();
  const realFreeAgents: StaffMember[] = [];

  // 3. Process Real Staff
  realStaffRaw.forEach(raw => {
    // Calculate Reputation
    const reputation = calculateStaffReputation(raw as any, 2026); // Assume 2026 start

    // Calculate Salary Expectation
    const salaryExpectation = calculateSalaryExpectation(raw.role, raw.skills, reputation, raw.archetype);

    // Complete Staff Object
    // We cast raw to any to access _schoolName safely
    const rawAny = raw as any;

    const staff: StaffMember = {
      id: raw.id,
      name: raw.name,
      role: raw.role,
      skills: raw.skills,
      archetype: raw.archetype,
      partnerId: raw.partnerId,
      historyText: raw.historyText,
      achievements: raw.achievements,
      reputation,
      salaryExpectation,
      salary: 0,
      contractYears: 0,
      currentSchoolId: null // Will be set below
    };

    // Find Target School
    const targetSchool = schools.find(s => s.name === rawAny._schoolName);

    if (targetSchool) {
      // Assign to School
      staff.currentSchoolId = targetSchool.id;
      staff.contractYears = 1; // Assume 1 year contract
      staff.salary = salaryExpectation; // Assume they are paid their worth

      // Remove existing GENERIC staff in that role if any.
      // We keep other Real Staff (e.g. for Duos like Gabriel Haddad & Leonardo Bora).
      const genericStaffInRole = targetSchool.staff.filter(s =>
        s.role === staff.role &&
        !realStaffRaw.some(r => r.id === s.id)
      );

      genericStaffInRole.forEach(generic => {
        const idx = targetSchool.staff.indexOf(generic);
        if (idx !== -1) targetSchool.staff.splice(idx, 1);
      });

      targetSchool.staff.push(staff);
    } else {
      // Free Agent (e.g. SP schools not in DB)
      realFreeAgents.push(staff);
    }
  });

  // 4. Load Random Market Staff (Initial)
  // Filter out names that exist in realStaff to avoid duplicates (e.g. Paulo Barros generated by seed)
  const realNames = new Set(realStaffRaw.map(s => s.name));

  const marketStaff = INITIAL_MARKET_STAFF.filter(s => !realNames.has(s.name));

  // Combine Free Agents
  // We put realFreeAgents FIRST so they appear at the top
  const availableStaff = [...realFreeAgents, ...marketStaff];

  return { schools, availableStaff };
};

const { schools: initialSchools, availableStaff: initialStaff } = initializeGameData();

/**
 * Calculates the displayed salary expectation adjusted by the school's prestige.
 * Higher prestige schools see a lower "effective price" because staff want to work there.
 */
export const calculateAdjustedSalary = (staff: StaffMember, schoolPrestige: number): number => {
  if (staff.role === 'RainhaDeBateria' && staff.archetype !== 'CriaDaComunidade') {
    return 0; // Celebrity and PostoPago don't have salary negotiation in the same way
  }

  const prestigeMultiplier = 1 + ((schoolPrestige - 100) / 500);
  const safeMultiplier = Math.max(0.1, prestigeMultiplier);

  return Math.ceil(staff.salaryExpectation / safeMultiplier);
};

/**
 * GameStoreState defines the shape of the global game state managed by Zustand.
 * It includes the current game status, the list of schools, and actions to modify the state.
 */
interface GameStoreState {
  gameState: GameState;
  schools: School[];
  availableStaff: StaffMember[];
  simulationResults: SimulationResult | null;

  // Actions
  setPlayerSchool: (schoolId: string) => void;
  advanceWeek: () => void;
  submitTransferOffer: (schoolId: string, staffId: string, offeredSalary: number, contractYears: number) => string;
  acceptCounter: (offerId: string) => void;
  rejectCounter: (offerId: string) => void;
  generateTheme: (schoolId: string, budgetInvested: number) => void;
  runPrestigeSimulation: (years: number) => void;
}

/**
 * useGameStore is the Zustand hook for accessing and updating the game state.
 * It initializes with the seed data and default game state.
 */
export const useGameStore = create<GameStoreState>((set, get) => ({
  gameState: {
    currentYear: 2026,
    currentWeek: 1,
    currentPhase: 'Market',
    playerSchoolId: null,
    pendingOffers: [],
    resolvedOffers: [],
    transferNews: []
  },
  schools: initialSchools,
  availableStaff: initialStaff,
  simulationResults: null,

  setPlayerSchool: (schoolId) =>
    set((state) => {
      const updatedSchools = state.schools.map((school) => ({
        ...school,
        isPlayerControlled: school.id === schoolId,
      }));

      return {
        schools: updatedSchools,
        gameState: {
          ...state.gameState,
          playerSchoolId: schoolId,
        },
      };
    }),

  advanceWeek: () =>
    set((state) => {
      // 1. Process Logic for current week (before advancing)
      const { currentYear, currentWeek, currentPhase, pendingOffers } = state.gameState;

      let updatedSchools = [...state.schools];
      let updatedAvailableStaff = [...state.availableStaff];
      let newResolvedOffers = [...state.gameState.resolvedOffers]; // Keep existing resolved offers? Prompt says "cleared each week after display"
      // Actually prompt says "Close button clears resolvedOffers...". But here we should probably clear old ones if they were viewed?
      // Or maybe we clear them now?
      // "The player sees all results... at the start of each new week."
      // So we should probably keep them until the player dismisses them, OR accumulate new ones.
      // Prompt: "Close button clears resolvedOffers and transferNews from view (but not from state until next week)"
      // Actually: "Close button clears resolvedOffers... from view".
      // Let's assume we clear *previous* week's resolved offers when we resolve *new* ones, effectively replacing them.
      // So reset resolvedOffers to [].
      newResolvedOffers = [];

      let newTransferNews = [...state.gameState.transferNews]; // Accumulate? Or reset?
      // Prompt: "list transferNews strings from AI market activity log".
      // Usually news is weekly.
      newTransferNews = [];

      if (currentPhase === 'Market') {
        // A. Resolve Player Offers
        const pending = [...pendingOffers];

        pending.forEach(offer => {
            if (offer.status !== 'Pending') {
                // Should not be here usually, but if so, move to resolved
                newResolvedOffers.push(offer);
                return;
            }

            const schoolIdx = updatedSchools.findIndex(s => s.id === offer.fromSchoolId);
            const staffIdx = updatedAvailableStaff.findIndex(s => s.id === offer.toStaffId);
            let staff = updatedAvailableStaff[staffIdx];

            // If staff not in available, maybe they are in another school?
            if (!staff) {
                // Check schools
                for (const s of updatedSchools) {
                    const found = s.staff.find(st => st.id === offer.toStaffId);
                    if (found) {
                        staff = found;
                        break;
                    }
                }
            }

            if (!staff || schoolIdx === -1) {
                // Invalid offer (staff retired? school gone?)
                offer.status = 'Rejected';
                newResolvedOffers.push(offer);
                return;
            }

            const school = updatedSchools[schoolIdx];
            const resolved = resolveOffer(offer, staff, school);

            if (resolved.status === 'Accepted') {
                // Execute Hire
                // 1. Remove from old location
                if (staff.currentSchoolId) {
                    const oldSchoolIdx = updatedSchools.findIndex(s => s.id === staff.currentSchoolId);
                    if (oldSchoolIdx !== -1) {
                        const oldSchool = updatedSchools[oldSchoolIdx];
                        oldSchool.staff = oldSchool.staff.filter(s => s.id !== staff.id);
                        updatedSchools[oldSchoolIdx] = { ...oldSchool };
                    }
                } else {
                    // Remove from available
                    updatedAvailableStaff = updatedAvailableStaff.filter(s => s.id !== staff.id);
                }

                // 2. Remove existing staff in role at new school
                const existingStaffIdx = school.staff.findIndex(s => s.role === staff.role);
                if (existingStaffIdx !== -1) {
                    const fired = school.staff[existingStaffIdx];
                    fired.currentSchoolId = null;
                    fired.salary = 0;
                    fired.contractYears = 0;
                    updatedAvailableStaff.push(fired);

                    school.staff = school.staff.filter(s => s.id !== fired.id); // Remove from roster
                }

                // 3. Add to new school
                const newStaff = {
                    ...staff,
                    currentSchoolId: school.id,
                    salary: offer.offeredSalary,
                    contractYears: offer.contractYears
                };
                school.staff.push(newStaff);

                // 4. Update Budget
                // Rainha logic? Prompt didn't mention specific Rainha logic for *transfers*, but we should probably keep it consistent?
                // "The project is a 'Carnival Manager'... RainhaDeBateria roles have specific archetypes..."
                // Transfer service ignores Rainha logic?
                // `calculateOfferProbability` works for everyone.
                // But budget deduction?
                // Standard logic: deduct salary.
                // Rainha special logic (PostoPago adds money, Celebrity costs 0?)
                // If the user manually offered a salary, we deduct it.
                // If it's PostoPago, salary offered might be 0, but they pay the school.
                // Let's assume Transfer System overrides the "Instant Hire" special logic for now, or applies it if appropriate.
                // Given the prompt didn't specify Rainha transfer details, I'll stick to simple deduction of offered salary.
                school.budget -= offer.offeredSalary;

                // 5. Prestige Bonus
                const prestigeBonus = Math.max(0, (staff.reputation - school.prestige) * 0.02);
                school.prestige = Math.min(195, school.prestige + prestigeBonus);

                updatedSchools[schoolIdx] = { ...school };
            }

            newResolvedOffers.push(resolved);
        });

        // B. Run AI Transfers
        const aiResult = processAITransfers(updatedSchools, updatedAvailableStaff, currentWeek);
        updatedSchools = aiResult.updatedSchools;
        updatedAvailableStaff = aiResult.updatedStaff;
        newTransferNews = aiResult.news;
      }

      // 2. Advance Time
      let nextWeek = currentWeek + 1;
      let nextYear = currentYear;

      if (nextWeek > 52) {
        nextWeek = 1;
        nextYear += 1;
      }

      let nextPhase: GameState['currentPhase'] = 'Market';
      if (nextWeek >= 1 && nextWeek <= 12) {
        nextPhase = 'Market';
      } else if (nextWeek >= 13 && nextWeek <= 44) {
        nextPhase = 'Preparation';
      } else if (nextWeek === 45) {
        nextPhase = 'Parade';
      } else {
        nextPhase = 'Results/Offseason';
      }

      return {
        schools: updatedSchools,
        availableStaff: updatedAvailableStaff,
        gameState: {
          ...state.gameState,
          currentYear: nextYear,
          currentWeek: nextWeek,
          currentPhase: nextPhase,
          pendingOffers: [], // All pending were resolved (or moved to resolvedOffers)
          resolvedOffers: newResolvedOffers,
          transferNews: newTransferNews
        },
      };
    }),

  submitTransferOffer: (schoolId, staffId, offeredSalary, contractYears) => {
    const state = get();
    const { currentWeek, currentPhase, pendingOffers } = state.gameState;

    if (currentPhase !== 'Market') return 'Transfer market is closed.';

    const school = state.schools.find(s => s.id === schoolId);
    // Find staff in available OR in other schools
    let staff = state.availableStaff.find(s => s.id === staffId);
    if (!staff) {
        for (const s of state.schools) {
            staff = s.staff.find(st => st.id === staffId);
            if (staff) break;
        }
    }

    if (!school) return 'School not found.';
    if (!staff) return 'Staff not found.';

    if (school.budget < offeredSalary) return 'Insufficient budget.';

    // Check one offer per role per week
    const conflict = pendingOffers.find(o => {
        if (o.fromSchoolId !== schoolId || o.status !== 'Pending' || o.weekMade !== currentWeek) return false;

        // Check role
        let targetStaff = state.availableStaff.find(s => s.id === o.toStaffId);
        if (!targetStaff) {
             for (const s of state.schools) {
                targetStaff = s.staff.find(st => st.id === o.toStaffId);
                if (targetStaff) break;
            }
        }
        return targetStaff && targetStaff.role === staff.role;
    });

    if (conflict) return 'You can only make one offer per role per week.';

    const offer: TransferOffer = {
        id: `offer-${Date.now()}-${Math.random()}`,
        fromSchoolId: schoolId,
        toStaffId: staffId,
        offeredSalary,
        contractYears,
        weekMade: currentWeek,
        status: 'Pending'
    };

    set(state => ({
        gameState: {
            ...state.gameState,
            pendingOffers: [...state.gameState.pendingOffers, offer]
        }
    }));

    return 'Offer submitted successfully.';
  },

  acceptCounter: (offerId) => {
    const state = get();
    const offerIndex = state.gameState.resolvedOffers.findIndex(o => o.id === offerId);
    if (offerIndex === -1) return;

    const offer = state.gameState.resolvedOffers[offerIndex];
    if (offer.status !== 'Countered' || !offer.counterSalary) return;

    // Execute Hire (Copy-paste logic from resolve, but using counter values)
    // We need to update schools and staff
    const updatedSchools = [...state.schools];
    let updatedAvailableStaff = [...state.availableStaff];

    const schoolIdx = updatedSchools.findIndex(s => s.id === offer.fromSchoolId);
    let staff = updatedAvailableStaff.find(s => s.id === offer.toStaffId);

    // Find staff if not available
    if (!staff) {
        for (const s of updatedSchools) {
            const found = s.staff.find(st => st.id === offer.toStaffId);
            if (found) {
                staff = found;
                break;
            }
        }
    }

    if (schoolIdx === -1 || !staff) return; // Should handle error?
    const school = updatedSchools[schoolIdx];

    if (school.budget < offer.counterSalary) {
        // Can't afford counter?
        // UI should prevent this probably, but handle here.
        // Fail silently or just don't apply.
        return;
    }

    // Execute Hire
    // 1. Remove from old
    if (staff.currentSchoolId) {
        const oldSchoolIdx = updatedSchools.findIndex(s => s.id === staff.currentSchoolId);
        if (oldSchoolIdx !== -1) {
            const oldSchool = updatedSchools[oldSchoolIdx];
            oldSchool.staff = oldSchool.staff.filter(s => s.id !== staff!.id); // ! is safe here
            updatedSchools[oldSchoolIdx] = { ...oldSchool };
        }
    } else {
        updatedAvailableStaff = updatedAvailableStaff.filter(s => s.id !== staff!.id);
    }

    // 2. Remove existing
    const existingStaffIdx = school.staff.findIndex(s => s.role === staff!.role);
    if (existingStaffIdx !== -1) {
        const fired = school.staff[existingStaffIdx];
        fired.currentSchoolId = null;
        fired.salary = 0;
        fired.contractYears = 0;
        updatedAvailableStaff.push(fired);
        school.staff = school.staff.filter(s => s.id !== fired.id);
    }

    // 3. Add new
    const newStaff = {
        ...staff,
        currentSchoolId: school.id,
        salary: offer.counterSalary,
        contractYears: offer.counterYears || 1
    };
    school.staff.push(newStaff);

    // 4. Budget
    school.budget -= offer.counterSalary;

    // 5. Prestige
    const prestigeBonus = Math.max(0, (staff.reputation - school.prestige) * 0.02);
    school.prestige = Math.min(195, school.prestige + prestigeBonus);

    updatedSchools[schoolIdx] = { ...school };

    // Update Offer Status
    const updatedResolvedOffers = [...state.gameState.resolvedOffers];
    updatedResolvedOffers[offerIndex] = { ...offer, status: 'Accepted' };

    set({
        schools: updatedSchools,
        availableStaff: updatedAvailableStaff,
        gameState: {
            ...state.gameState,
            resolvedOffers: updatedResolvedOffers
        }
    });
  },

  rejectCounter: (offerId) => {
    set(state => ({
        gameState: {
            ...state.gameState,
            resolvedOffers: state.gameState.resolvedOffers.map(o =>
                o.id === offerId ? { ...o, status: 'Rejected' } : o
            )
        }
    }));
  },

  generateTheme: (schoolId, budgetInvested) => {
    const state = get();
    const schoolIndex = state.schools.findIndex((s) => s.id === schoolId);
    if (schoolIndex === -1) return;

    const school = state.schools[schoolIndex];

    if (school.budget < budgetInvested) {
      console.warn("Not enough budget for research");
      return;
    }

    const carnavalesco = school.staff.find((s) => s.role === 'Carnavalesco');
    let skill = 50;
    if (carnavalesco) {
      skill = (carnavalesco.skills.criatividade * 0.7) + (carnavalesco.skills.resiliencia * 0.3);
    }

    const newEnredo = researchEnredo(skill, budgetInvested);

    const updatedSchools = [...state.schools];
    updatedSchools[schoolIndex] = {
      ...school,
      budget: school.budget - budgetInvested,
      enredo: newEnredo,
    };

    set({ schools: updatedSchools });
  },

  runPrestigeSimulation: (years) => {
    const state = get();
    const results = runSimulation(state.schools, state.gameState.currentYear, years);
    set({ simulationResults: results });
  },
}));
