import { create } from 'zustand';
import { GameState, School, StaffMember, TransferOffer } from '../types/models';
import { loadAllSchools } from '../data/schoolLoader';
import { INITIAL_MARKET_STAFF } from '../data/staffSeed';
import { calculateSalaryExpectation, ALL_ROLES } from '../utils/staffUtils';
import { loadRealStaff } from '../data/realStaff';
import { calculateStaffReputation, processRetirements, processStaffDevelopment } from '../services/staffService';
import { researchEnredo } from '../services/researchEngine';
import { runSimulation, SimulationResult } from '../services/simulationService';
import { resolveOffer, processAITransfers } from '../services/transferService';

/**
 * Helper to initialize game data by merging real staff into schools and market.
 */
const initializeGameData = () => {
  // 1. Load Schools
  const schools = loadAllSchools();

  // 2. Load Real Staff
  const realStaffRaw = loadRealStaff();
  const realFreeAgents: StaffMember[] = [];

  // 3. Process Real Staff
  realStaffRaw.forEach(raw => {
    // Calculate Reputation
    const reputation = calculateStaffReputation(raw as any, 2026); // Assume 2026 start

    // Calculate Salary Expectation
    const salaryExpectation = calculateSalaryExpectation(raw.role, raw.skills, reputation, raw.archetype);

    // Complete Staff Object
    // We cast raw to any to access _schoolName safely
    const rawAny = raw as any;

    const staff: StaffMember = {
      id: raw.id,
      name: raw.name,
      role: raw.role,
      skills: raw.skills,
      archetype: raw.archetype,
      partnerId: raw.partnerId,
      historyText: raw.historyText,
      achievements: raw.achievements,
      reputation,
      salaryExpectation,
      salary: 0,
      contractYears: 0,
      currentSchoolId: null, // Will be set below
      age: raw.age,
      potential: undefined // Real staff have no potential (ceiling reached or custom logic)
    };

    // Find Target School
    const targetSchool = schools.find(s => s.name === rawAny._schoolName);

    if (targetSchool) {
      // Assign to School
      staff.currentSchoolId = targetSchool.id;
      staff.contractYears = 1; // Assume 1 year contract
      staff.salary = salaryExpectation; // Assume they are paid their worth

      // Remove existing GENERIC staff in that role if any.
      // We keep other Real Staff (e.g. for Duos like Gabriel Haddad & Leonardo Bora).
      const genericStaffInRole = targetSchool.staff.filter(s =>
        s.role === staff.role &&
        !realStaffRaw.some(r => r.id === s.id)
      );

      genericStaffInRole.forEach(generic => {
        const idx = targetSchool.staff.indexOf(generic);
        if (idx !== -1) targetSchool.staff.splice(idx, 1);
      });

      targetSchool.staff.push(staff);
    } else {
      // Free Agent (e.g. SP schools not in DB)
      realFreeAgents.push(staff);
    }
  });

  // 4. Load Random Market Staff (Initial)
  // Filter out names that exist in realStaff to avoid duplicates (e.g. Paulo Barros generated by seed)
  const realNames = new Set(realStaffRaw.map(s => s.name));

  const marketStaff = INITIAL_MARKET_STAFF.filter(s => !realNames.has(s.name));

  // Combine Free Agents
  // We put realFreeAgents FIRST so they appear at the top
  const availableStaff = [...realFreeAgents, ...marketStaff];

  return { schools, availableStaff };
};

const { schools: initialSchools, availableStaff: initialStaff } = initializeGameData();

/**
 * Calculates the displayed salary expectation adjusted by the school's prestige.
 * Higher prestige schools see a lower "effective price" because staff want to work there.
 */
export const calculateAdjustedSalary = (staff: StaffMember, schoolPrestige: number): number => {
  if (staff.role === 'RainhaDeBateria' && staff.archetype !== 'CriaDaComunidade') {
    return 0; // Celebrity and PostoPago don't have salary negotiation in the same way
  }

  const prestigeMultiplier = 1 + ((schoolPrestige - 100) / 500);
  const safeMultiplier = Math.max(0.1, prestigeMultiplier);

  return Math.ceil(staff.salaryExpectation / safeMultiplier);
};

/**
 * GameStoreState defines the shape of the global game state managed by Zustand.
 * It includes the current game status, the list of schools, and actions to modify the state.
 */
interface GameStoreState {
  gameState: GameState;
  schools: School[];
  availableStaff: StaffMember[];
  simulationResults: SimulationResult | null;

  // Actions
  setPlayerSchool: (schoolId: string) => void;
  advanceWeek: () => void;
  submitTransferOffer: (schoolId: string, staffId: string, offeredSalary: number, contractYears: number) => string;
  acceptCounter: (offerId: string) => void;
  rejectCounter: (offerId: string) => void;
  generateTheme: (schoolId: string, budgetInvested: number) => void;
  runPrestigeSimulation: (years: number) => void;
}

/**
 * useGameStore is the Zustand hook for accessing and updating the game state.
 * It initializes with the seed data and default game state.
 */
export const useGameStore = create<GameStoreState>((set, get) => ({
  gameState: {
    currentYear: 2026,
    currentWeek: 1,
    currentPhase: 'Market',
    playerSchoolId: null,
    pendingOffers: [],
    resolvedOffers: [],
    transferNews: [],
    hallOfFame: []
  },
  schools: initialSchools,
  availableStaff: initialStaff,
  simulationResults: null,

  setPlayerSchool: (schoolId) =>
    set((state) => {
      const updatedSchools = state.schools.map((school) => ({
        ...school,
        isPlayerControlled: school.id === schoolId,
      }));

      return {
        schools: updatedSchools,
        gameState: {
          ...state.gameState,
          playerSchoolId: schoolId,
        },
      };
    }),

  advanceWeek: () =>
    set((state) => {
      // 1. Process Logic for current week (before advancing)
      const { currentYear, currentWeek, currentPhase, pendingOffers } = state.gameState;

      let updatedSchools = [...state.schools];
      let updatedAvailableStaff = [...state.availableStaff];
      let newResolvedOffers = [...state.gameState.resolvedOffers];
      // Close button clears resolvedOffers from view, so we assume we start fresh or append.
      // Given the UI logic, let's clear them so we only show new ones.
      newResolvedOffers = [];

      let newTransferNews = [...state.gameState.transferNews];
      // Reset news? Usually yes for a new week update.
      newTransferNews = [];

      if (currentPhase === 'Market') {
        // A. Resolve Player Offers
        const pending = [...pendingOffers];

        pending.forEach(offer => {
            if (offer.status !== 'Pending') {
                newResolvedOffers.push(offer);
                return;
            }

            const schoolIdx = updatedSchools.findIndex(s => s.id === offer.fromSchoolId);
            const staffIdx = updatedAvailableStaff.findIndex(s => s.id === offer.toStaffId);
            let staff = updatedAvailableStaff[staffIdx];

            if (!staff) {
                // Check schools
                for (const s of updatedSchools) {
                    const found = s.staff.find(st => st.id === offer.toStaffId);
                    if (found) {
                        staff = found;
                        break;
                    }
                }
            }

            if (!staff || schoolIdx === -1) {
                offer.status = 'Rejected';
                newResolvedOffers.push(offer);
                return;
            }

            const school = updatedSchools[schoolIdx];
            const unfilledRolesCount = ALL_ROLES.filter(role => !school.staff.some(s => s.role === role)).length;

            const resolved = resolveOffer(offer, staff, school, currentWeek, 8, unfilledRolesCount);

            if (resolved.status === 'Accepted') {
                // Execute Hire
                if (staff.currentSchoolId) {
                    const oldSchoolIdx = updatedSchools.findIndex(s => s.id === staff.currentSchoolId);
                    if (oldSchoolIdx !== -1) {
                        const oldSchool = updatedSchools[oldSchoolIdx];
                        oldSchool.staff = oldSchool.staff.filter(s => s.id !== staff.id);
                        updatedSchools[oldSchoolIdx] = { ...oldSchool };
                    }
                } else {
                    updatedAvailableStaff = updatedAvailableStaff.filter(s => s.id !== staff.id);
                }

                const existingStaffIdx = school.staff.findIndex(s => s.role === staff.role);
                if (existingStaffIdx !== -1) {
                    const fired = school.staff[existingStaffIdx];
                    fired.currentSchoolId = null;
                    fired.salary = 0;
                    fired.contractYears = 0;
                    updatedAvailableStaff.push(fired);
                    school.staff = school.staff.filter(s => s.id !== fired.id);
                }

                const newStaff = {
                    ...staff,
                    currentSchoolId: school.id,
                    salary: offer.offeredSalary,
                    contractYears: offer.contractYears
                };
                school.staff.push(newStaff);
                school.budget -= offer.offeredSalary;

                const prestigeBonus = Math.max(0, (staff.reputation - school.prestige) * 0.02);
                school.prestige = Math.min(195, school.prestige + prestigeBonus);

                updatedSchools[schoolIdx] = { ...school };
            }

            newResolvedOffers.push(resolved);
        });

        // B. Run AI Transfers
        const aiResult = processAITransfers(updatedSchools, updatedAvailableStaff, currentWeek, 8);
        updatedSchools = aiResult.updatedSchools;
        updatedAvailableStaff = aiResult.updatedStaff;
        newTransferNews = aiResult.news;
      }

      // 2. Advance Time
      let nextWeek = currentWeek + 1;
      let nextYear = currentYear;

      if (nextWeek > 52) {
        nextWeek = 1;
        nextYear += 1;
      }

      let nextPhase: GameState['currentPhase'] = 'Market';
      if (nextWeek >= 1 && nextWeek <= 8) {
        nextPhase = 'Market';
      } else if (nextWeek >= 9 && nextWeek <= 44) {
        nextPhase = 'Preparation';
      } else if (nextWeek === 45) {
        nextPhase = 'Parade';
      } else {
        nextPhase = 'Results/Offseason';
      }

      // -- NEW LOGIC START --

      // Retirement Check (Start of Market / Week 1)
      let hallOfFame = [...state.gameState.hallOfFame || []];

      if (nextWeek === 1) {
          // Process Available Staff
          const retAvail = processRetirements(updatedAvailableStaff);
          updatedAvailableStaff = retAvail.remaining;

          retAvail.retired.forEach(r => {
              if (r.reputation >= 200) hallOfFame.push(r);
              newTransferNews.push(`${r.name} (${r.role}) retired.`);
          });

          // Process Schools Staff
          updatedSchools = updatedSchools.map(school => {
             const retSchool = processRetirements(school.staff);

             retSchool.retired.forEach(r => {
                 if (r.reputation >= 200) hallOfFame.push(r);
                 newTransferNews.push(`${r.name} (${r.role}, ${school.name}) retired.`);
             });

             return { ...school, staff: retSchool.remaining };
          });
      }

      // Development Check (Start of Results/Offseason)
      if (nextWeek === 46) {
          // Process Player School Development
          const playerSchoolIndex = updatedSchools.findIndex(s => s.id === state.gameState.playerSchoolId);
          if (playerSchoolIndex !== -1) {
              const playerSchool = updatedSchools[playerSchoolIndex];
              // Get Score
              let score = 50;
              // Simple heuristic if no simulation result available
              if (playerSchool.prestige > 150) score = 70 + (Math.random() * 20);
              else score = 50 + (Math.random() * 20);

              const devResult = processStaffDevelopment(playerSchool.staff, score);
              updatedSchools[playerSchoolIndex] = { ...playerSchool, staff: devResult.updatedStaff };

              devResult.updates.forEach(u => newTransferNews.push(u));
          }
      }
      // -- NEW LOGIC END --

      return {
        schools: updatedSchools,
        availableStaff: updatedAvailableStaff,
        gameState: {
          ...state.gameState,
          currentYear: nextYear,
          currentWeek: nextWeek,
          currentPhase: nextPhase,
          pendingOffers: [],
          resolvedOffers: newResolvedOffers,
          transferNews: newTransferNews,
          hallOfFame
        },
      };
    }),

  submitTransferOffer: (schoolId, staffId, offeredSalary, contractYears) => {
    const state = get();
    const { currentWeek, currentPhase, pendingOffers } = state.gameState;

    if (currentPhase !== 'Market') return 'Transfer market is closed.';

    const school = state.schools.find(s => s.id === schoolId);
    let staff = state.availableStaff.find(s => s.id === staffId);
    if (!staff) {
        for (const s of state.schools) {
            staff = s.staff.find(st => st.id === staffId);
            if (staff) break;
        }
    }

    if (!school) return 'School not found.';
    if (!staff) return 'Staff not found.';

    if (school.budget < offeredSalary) return 'Insufficient budget.';

    const conflict = pendingOffers.find(o => {
        if (o.fromSchoolId !== schoolId || o.status !== 'Pending' || o.weekMade !== currentWeek) return false;
        let targetStaff = state.availableStaff.find(s => s.id === o.toStaffId);
        if (!targetStaff) {
             for (const s of state.schools) {
                targetStaff = s.staff.find(st => st.id === o.toStaffId);
                if (targetStaff) break;
            }
        }
        return targetStaff && targetStaff.role === staff.role;
    });

    if (conflict) return 'You can only make one offer per role per week.';

    const offer: TransferOffer = {
        id: `offer-${Date.now()}-${Math.random()}`,
        fromSchoolId: schoolId,
        toStaffId: staffId,
        offeredSalary,
        contractYears,
        weekMade: currentWeek,
        status: 'Pending'
    };

    set(state => ({
        gameState: {
            ...state.gameState,
            pendingOffers: [...state.gameState.pendingOffers, offer]
        }
    }));

    return 'Offer submitted successfully.';
  },

  acceptCounter: (offerId) => {
    const state = get();
    const offerIndex = state.gameState.resolvedOffers.findIndex(o => o.id === offerId);
    if (offerIndex === -1) return;

    const offer = state.gameState.resolvedOffers[offerIndex];
    if (offer.status !== 'Countered' || !offer.counterSalary) return;

    const updatedSchools = [...state.schools];
    let updatedAvailableStaff = [...state.availableStaff];

    const schoolIdx = updatedSchools.findIndex(s => s.id === offer.fromSchoolId);
    let staff = updatedAvailableStaff.find(s => s.id === offer.toStaffId);

    if (!staff) {
        for (const s of updatedSchools) {
            const found = s.staff.find(st => st.id === offer.toStaffId);
            if (found) {
                staff = found;
                break;
            }
        }
    }

    if (schoolIdx === -1 || !staff) return;
    const school = updatedSchools[schoolIdx];

    if (school.budget < offer.counterSalary) {
        return;
    }

    if (staff.currentSchoolId) {
        const oldSchoolIdx = updatedSchools.findIndex(s => s.id === staff.currentSchoolId);
        if (oldSchoolIdx !== -1) {
            const oldSchool = updatedSchools[oldSchoolIdx];
            oldSchool.staff = oldSchool.staff.filter(s => s.id !== staff!.id);
            updatedSchools[oldSchoolIdx] = { ...oldSchool };
        }
    } else {
        updatedAvailableStaff = updatedAvailableStaff.filter(s => s.id !== staff!.id);
    }

    const existingStaffIdx = school.staff.findIndex(s => s.role === staff!.role);
    if (existingStaffIdx !== -1) {
        const fired = school.staff[existingStaffIdx];
        fired.currentSchoolId = null;
        fired.salary = 0;
        fired.contractYears = 0;
        updatedAvailableStaff.push(fired);
        school.staff = school.staff.filter(s => s.id !== fired.id);
    }

    const newStaff = {
        ...staff,
        currentSchoolId: school.id,
        salary: offer.counterSalary,
        contractYears: offer.counterYears || 1
    };
    school.staff.push(newStaff);
    school.budget -= offer.counterSalary;

    const prestigeBonus = Math.max(0, (staff.reputation - school.prestige) * 0.02);
    school.prestige = Math.min(195, school.prestige + prestigeBonus);

    updatedSchools[schoolIdx] = { ...school };

    const updatedResolvedOffers = [...state.gameState.resolvedOffers];
    updatedResolvedOffers[offerIndex] = { ...offer, status: 'Accepted' };

    set({
        schools: updatedSchools,
        availableStaff: updatedAvailableStaff,
        gameState: {
            ...state.gameState,
            resolvedOffers: updatedResolvedOffers
        }
    });
  },

  rejectCounter: (offerId) => {
    set(state => ({
        gameState: {
            ...state.gameState,
            resolvedOffers: state.gameState.resolvedOffers.map(o =>
                o.id === offerId ? { ...o, status: 'Rejected' } : o
            )
        }
    }));
  },

  generateTheme: (schoolId, budgetInvested) => {
    const state = get();
    const schoolIndex = state.schools.findIndex((s) => s.id === schoolId);
    if (schoolIndex === -1) return;

    const school = state.schools[schoolIndex];

    if (school.budget < budgetInvested) {
      console.warn("Not enough budget for research");
      return;
    }

    const carnavalesco = school.staff.find((s) => s.role === 'Carnavalesco');
    let skill = 50;
    if (carnavalesco) {
      skill = (carnavalesco.skills.criatividade * 0.7) + (carnavalesco.skills.resiliencia * 0.3);
    }

    const newEnredo = researchEnredo(skill, budgetInvested);

    const updatedSchools = [...state.schools];
    updatedSchools[schoolIndex] = {
      ...school,
      budget: school.budget - budgetInvested,
      enredo: newEnredo,
    };

    set({ schools: updatedSchools });
  },

  runPrestigeSimulation: (years) => {
    const state = get();
    const results = runSimulation(state.schools, state.gameState.currentYear, years);
    set({ simulationResults: results });
  },
}));
